// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  projects: dynamic(() => import('./Projects')),
  rich_text: dynamic(() => import('./RichText')),
  websites: dynamic(() => import('./Websites')),
};
